sudo: required

language: php
php:
  - '7.0'

stages:
  - analyse
  - build

jobs:
  include:

    - stage: analyse
      env:
        - TEST=phplint
      before_script:
        - composer install
      script:
        - composer analyse:phplint

    - stage: analyse
      env:
        - TEST=phpcs
      before_script:
        - composer install
      script:
        - composer analyse:phpcs

    - stage: build
      before_script:
        - export SRC_BRANCH=${TRAVIS_BRANCH}
        - export SRC_PREFIX="src/"

        - export BUILD_BRANCH=${SRC_BRANCH#$SRC_PREFIX}

        - export AUTHOR_NAME=`git --no-pager show -s --format='%an'`
        - export AUTHOR_EMAIL=`git --no-pager show -s --format='%ae'`
      script:
        - make
      deploy:
        provider: pages
        github-token: ${GH_TOKEN}
        skip-cleanup: true
        keep-history: true
        target-branch: ${BUILD_BRANCH}
        email: ${AUTHOR_EMAIL}
        name: ${AUTHOR_NAME}
        verbose: true

notifications:
  webhooks:
    - https://h2a-hubot.herokuapp.com/webhooks/travis
