sudo: required

language: php
php:
  - '7.0'

stages:
  - analyse
  - build

jobs:
  include:

    - stage: analyse
      env:
        - TEST=phplint
      before_script:
        - composer install
      script:
        - composer analyse:phplint

    - stage: analyse
      env:
        - TEST=phpcs
      before_script:
        - composer install
      script:
        - composer analyse:phpcs

    - stage: build
      before_script:
        - export BUILD_HEAD=`git rev-parse HEAD`

        - export SRC_BRANCH=${TRAVIS_BRANCH}
        - export SRC_PREFIX="src/"

        - export BUILD_BRANCH=${SRC_BRANCH#$SRC_PREFIX}

        - export AUTHOR_NAME=`git --no-pager show -s --format='%an'`
        - export AUTHOR_EMAIL=`git --no-pager show -s --format='%ae'`

        - git config --global user.name "${AUTHOR_NAME}"
        - git config --global user.email "${AUTHOR_EMAIL}"

        - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
        - git fetch
        - |
          for branch in $(git branch -r|grep -v HEAD) ; do
            git checkout -qf ${branch#origin/}
          done
        - git checkout ${BUILD_HEAD}
      script:
        - make
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            if [ `git branch --list ${BUILD_BRANCH}` ]; then
              echo "Branch ${BUILD_BRANCH} already exists."
              git checkout ${BUILD_BRANCH}
            else
              echo "Creating branch ${BUILD_BRANCH}."
              git checkout --orphan ${BUILD_BRANCH}
            fi
            git add .
            git commit -m "${TRAVIS_COMMIT_MESSAGE}"
            git remote set-url origin "https://${GH_TOKEN}:x-oauth-basic@github.com/howtoadhd/wp-platform.git"
            git push origin "${BUILD_BRANCH}"
          fi

notifications:
  webhooks:
    - https://h2a-hubot.herokuapp.com/webhooks/travis
